# Site settings
title: Martin Jung
email: martinjung_NOSPAM_zoho.com
url: https://Martin-Jung.github.io
description: "Martin Jung personal webpage"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#222222'
  secondary: '#565656'
  links: '#4c924c'
  links-footer: '#CFCCA3'
  links-footer-hov: '#FEFEFD'

# Footer settings
footer: Martin Jung

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: email
    url: mailto:martinjung_NOSPAM_zoho
  - title: twitter
    url: http://twitter.com/Martin_Ecology
  - title: facebook
    url: http://www.facebook.com/martin.jung.5623
  - title: linkedin
    url: http://dk.linkedin.com/in/jungmartin/
  - title: wordpress
    url: http://conservationecology.wordpress.com
  - title: stack-exchange
    url: http://gis.stackexchange.com/users/6988/curlew
  - title: github
    url: https://github.com/Martin-Jung/
  - title: slideshare
    url: https://www.slideshare.net/MartinJung2
  - title: flickr
    url: http://www.flickr.com/people/44112305@N06/
  - title: researchgate
    url: https://www.researchgate.net/profile/Martin_Jung4
  - title: mendeley
    url: http://www.mendeley.com/profiles/martin-jung/


# Build settings
markdown: kramdown
permalink: pretty